### ISSUE TITLE
The empathetic_dialogue raw data does not have the field "emotion"

### ISSUE THREAD

**Issue by JieyuZ2** [varsha33/LCL_loss#4]
Do you mean "context" in the following code?

https://github.com/varsha33/LCL_loss/blob/master/data_preprocess.py#L44

**Comment by JieyuZ2** [comment]
Indeed, could you provide link to your processed data? I tried to use your code to preprocess raw data but failed :(

**Comment by varsha33** [comment]
Hi, sorry I did initial processing to the raw data of empathetic dialogues as it was conversation-based data and used that to perform the current pre-processing. I think that's why it didn't work for you. I have updated the repo with the "initial processing" script, ed_data_extract.py. Also, here is the link to the pre-processed files (https://drive.google.com/drive/folders/16MKEoGkTB5rY9SJ9hS7qMJp_dyOycKED?usp=sharing).

**Comment by JieyuZ2** [comment]
Thank you very much!
